// Toolbar button actions
export const TOOLBAR_ENTRY_DONE = 'TOOLBAR_ENTRY_DONE';
export const TOOLBAR_REFRESH = 'TOOLBAR_REFRESH';
export const TOOLBAR_DELETE = 'TOOLBAR_DELETE';
export const TOOLBAR_FILTER = 'TOOLBAR_FILTER';
export const TOOLBAR_MERGE_HELP = 'TOOLBAR_MERGE_HELP';
